"""add_personas_and_agent_sessions

Revision ID: 05da0926b866
Revises: aa402c5eb151
Create Date: 2026-04-13 15:17:35.218285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05da0926b866'
down_revision: Union[str, None] = 'aa402c5eb151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
