"""add_projects_and_project_scoping

Revision ID: 62c8463236e0
Revises: 6cdd71b200dc
Create Date: 2026-04-12 19:45:28.587944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c8463236e0'
down_revision: Union[str, None] = '6cdd71b200dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_linear_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('linear_project_id', sa.String(length=64), nullable=False),
    sa.Column('linear_project_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_linear_links_project_id'), 'project_linear_links', ['project_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='projectstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.add_column('chat_messages', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chat_messages_project_id'), 'chat_messages', ['project_id'], unique=False)
    op.add_column('notifications', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notifications_project_id'), 'notifications', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_project_id'), table_name='notifications')
    op.drop_column('notifications', 'project_id')
    op.drop_index(op.f('ix_chat_messages_project_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'project_id')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_project_linear_links_project_id'), table_name='project_linear_links')
    op.drop_table('project_linear_links')
    # ### end Alembic commands ###
